# Generated by Django 6.0 on 2026-01-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_emailotp_rename_user_accounts_useraccounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOtp',
        ),
    ]
